name: Rust
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: self-hosted
    container:
      image: santorini.home.arpa/library/ubuntu:22.04
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
            curl ca-certificates build-essential git pkg-config libssl-dev
    - name: Install packages
      run: |
        apt-get update && apt-get install -y curl \
          wget unzip pkg-config libssl-dev cmake build-essential
    - uses: actions/checkout@v4
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Install protoc
      run: |
        PROTOC_VERSION=27.2
        PROTOC_ZIP=protoc-$PROTOC_VERSION-linux-x86_64.zip
        wget https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP
        unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
        unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
    - name: Run clippy
      run: cargo clippy
    - name: Build tomis
      run: cargo build
    - name: Run tests
      run: cargo test
